# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e3db61a547f523c4682346ec5aba06d0b433497967c69157c760acebbc7b0d77a97c7aee0383cfec88863f93b6504419c92a6cd823da4cb9d029e5c22db1d8

test:
  secret_key_base: fdfb6a9a0af5435c2b13dfa0c6d29357539788b4d986ace4a52f2431e420738ece93560ef485e22065263108b712ded5796073f67ae32f506a0d86e2ce5a7ca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
